# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YTU5NzYxNDc0MGRlNmFmMDgwN2EzYzU4MmFjZjQzNGJkYTQxYmZkNzdkOTk4MTYwYzBkYmYxOGQ1ODRjOWJjZTQ1ODNlYzUzNDMwYjVmZDdlNzA4MzBmYTYwOTQ4YmVjMDU4YTk1MWY5NzY1MDUwODY4NmNmMDViNTJmZjVmNWQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
